### ISSUE TITLE
Expecting a demo

### ISSUE THREAD

**Issue by richlaji** [River-Zhang/GTA#1]
Hi, River-Zhang
    I'm studying papers on human body reconstruction, and I have read your paper. It is a very nice work! May I ask when will you update the open source? Expecting your demo~

**Comment by River-Zhang** [comment]
Thank you very much for reading our paper and for your positive feedback! We are glad to know you are interested in our work. Regarding the release of the open-source code, we are currently cleaning up the code to make it more understandable. Due to some parallel projects we are handling, it's challenging to manage time. However, we plan to open-source our code in late October or early November. By then, you will be able to find our code and demo. We look forward to you using our code, and any feedback after the release would be highly appreciated!

**Comment by richlaji** [comment]
Thank you for your reply! Hope everything goes well for you.

**Comment by River-Zhang** [comment]
Hi, richlaji! The code has been released. If there's any problem, please feel free to open issues. We'll try to solve them. Any feedback would be highly appreciated!

**Comment by River-Zhang** [comment]
Hi, richlaji! The code has been released. If there's any problem, please feel free to open issues. We'll try to solve them. Any feedback would be highly appreciated!

**Comment by richlaji** [comment]
> Hi, richlaji! The code has been released. If there's any problem, please feel free to open issues. We'll try to solve them. Any feedback would be highly appreciated!

Great!!!! Thank you for open source. I am going to try your code!
