### ISSUE TITLE
inference time

### ISSUE THREAD

**Issue by skunkwerk** [River-Zhang/GTA#3]
Hi, thanks for your great work.
I read your paper, but didn't see any mention of inference time for a single image.
Do you have a rough idea of what it would be on a modern GPU?

thanks!

**Comment by River-Zhang** [comment]
Thank you for your thoughtful feedback on our paper. We appreciate your interest in the inference time and implementation specifics. Due to the page constraints of the conference proceedings, we have detailed these aspects in the supplementary material, specifically in Sections E and A (for camera ready version, we may move these parts to the main paper).  Regarding inference, we utilize an optimization process for both SMPL and normal, resulting in an overall processing time of approximately **40 seconds** when using a single RTX 3090 GPU. In testing scenarios where SMPL ground truth (GT) is available, we bypass the optimization step, significantly reducing the geometry reconstruction time to roughly **0.55 seconds**.
