### ISSUE TITLE
Question about numbers, evaluation.

### ISSUE THREAD

**Issue by sdy-ny** [River-Zhang/GTA#9]
Hello I have two questions regarding the test results in your two papers GTA and SIFU. 

1. I see Issue #5 and your explanation in it. But I still don't understand why your GTA numbers for THuman 2.0 is different. 
In GTA paper, it is Chamfer 0.814, P2S 0.862, Normal 0.055. In SIFU, it is 0.73, 0.72, 0.04. 

2. I noticed that in both of your papers evaluation code, you are using GT front and back normal. This is different from ICON's evaluation protocol where they use estimated normal. (https://github.com/YuliangXiu/ICON/issues/183)
If using estimated normal, your GTA numbers for THuman 2.0 should be 1.12, 1.12, 0.065.

Could you please clarify these two points? Thank you!

**Comment by River-Zhang** [comment]
Thanks for your interest! We'll try to help you with your concerns. 
1. While training and testing SIFU model with THuman2.0, we find that some of the SMPL-X model in the dataset has wrong scales that can not fit the scan. This error might have been introduced during the dataset processing stage. So we reprocess the SMPL-X scans to make it right. And the testing results get better. (Note that other models (like GTA) mentioned in the SIFU paper are tested with the same dataset.)
2. We use GT normals and also GT SMPL-X during testing because we want to test purely our model's accuracy in reconstruction. This is also adopted by D-IF (a recent ICCV paper).  We test ICON in the same way, **so the comparisons in both papers are fair**. You can also change the code to use predicted normal to test the model's ability and their results may have a drop.
We hope that the answers above address your concerns. We are looking forward to your reply!
